import type { Metadata } from 'next';
import Image from 'next/image';
import { Mail, MapPin, Phone } from 'lucide-react';
import ConsultationForm from '@/components/contact/ConsultationForm';

export const metadata: Metadata = { title: 'Contact & Consultation | Macaney Sustainable Solutions', description: 'Book a consultation with Macaney Sustainable Solutions for premium beekeeping, apiary, and agtech support.' };

const contactDetails = [
  { icon: Mail, label: 'Email us', value: 'info@macaney\nsolutions.com' },
  { icon: Phone, label: 'Talk to our team', value: '+234 (0) 800 000 0000' },
  { icon: MapPin, label: 'Working across Africa', value: 'Nigeria · Africa' },
];

export default function ContactPage() {
  return <main className="overflow-hidden bg-stone-50 pt-16 text-stone-900 sm:pt-20"><section className="relative h-[23rem] overflow-hidden sm:h-[30rem] lg:h-[36rem]"><Image src="/images/beekeeper-harvesting-honey-with-bee-farm-and-production-vector.jpg" alt="Illustration of beekeepers harvesting and producing honey" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-amber-300/70 mix-blend-multiply" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(254,243,199,0.76)_0%,rgba(253,230,138,0.3)_54%,rgba(253,230,138,0.08)_100%)]" /><div className="relative mx-auto flex h-full max-w-7xl items-center px-4 pb-14 sm:px-6 sm:pb-20 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">Macaney consultations</p><h1 className="mt-4 font-serif text-4xl font-bold leading-[1.02] tracking-tight text-emerald-950 sm:text-6xl">Book a consultation with our team.</h1><p className="mt-5 max-w-xl text-base leading-7 text-emerald-950/85 sm:text-lg">From first hive to commercial scale, we bring thoughtful strategy, practical knowledge, and a deep respect for the landscape.</p></div></div><div aria-hidden="true" className="absolute -bottom-px left-1/2 h-16 w-[130%] -translate-x-1/2 rounded-t-[50%] bg-stone-50 sm:h-28" /></section><section className="relative mx-auto grid max-w-7xl gap-10 px-4 pb-20 pt-8 sm:px-6 sm:pb-28 sm:pt-12 lg:grid-cols-[minmax(0,0.95fr)_minmax(22rem,0.85fr)] lg:gap-16 lg:px-8"><div className="relative z-10"><ConsultationForm /></div><div className="relative pb-5 lg:pt-10"><div className="relative min-h-[32rem] overflow-hidden rounded-[2rem] bg-emerald-950 shadow-[0_28px_65px_-35px_rgba(6,78,59,0.75)] sm:min-h-[38rem]"><Image src="/images/723390758927351599.jpeg" alt="Beekeepers harvesting honey from a hive" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover object-center" /></div><div className="relative z-10 mx-5 -mt-8 grid gap-6 rounded-2xl border border-emerald-900/10 bg-white p-7 shadow-xl shadow-emerald-950/10 sm:mx-8 sm:p-8 xl:grid-cols-3 xl:gap-7">{contactDetails.map(({ icon: Icon, label, value }) => <div key={label} className="flex items-start gap-4 xl:block"><Icon className="mt-0.5 size-5 shrink-0 text-emerald-700 xl:mb-4" /><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-stone-500">{label}</p><p className="mt-1.5 whitespace-pre-line text-base font-semibold leading-6 text-emerald-950">{value}</p></div></div>)}</div></div></section></main>;
}
