import type { Metadata } from 'next';
import { ArrowRight, BadgeCheck, Leaf, Sprout, UsersRound } from 'lucide-react';
import Link from 'next/link';
import ServicesGrid from '@/components/services/ServicesGrid';
import { SERVICES } from '@/lib/services';

export const metadata: Metadata = { title: 'Services | Macaney Sustainable Solutions', description: 'Explore Macaney’s commercial apiary, agtech, training, and apiculture consultation services.' };

export default function ServicesPage() {
  return <main className="bg-[#f8f7f2] pt-20 text-stone-900 sm:pt-24"><section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 sm:pb-24 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h1 className="font-serif text-4xl font-bold leading-none tracking-tight text-emerald-950 sm:text-5xl">Cultivating sustainable success across every colony.</h1><p className="mt-4 text-sm leading-6 text-stone-600 sm:text-base">Whether you are launching a new apiary or expanding production, partner with Macaney for hands-on technical guidance, sustainable management frameworks, and reliable supply support.</p></div><div className="mt-10"><ServicesGrid services={SERVICES} /></div><section className="mt-10 rounded-2xl bg-emerald-950 px-6 py-8 text-white sm:px-8 sm:py-9"><h2 className="text-center font-serif text-2xl font-bold tracking-tight sm:text-3xl">Why work with Macaney?</h2><div className="mt-7 grid gap-7 sm:grid-cols-2 lg:grid-cols-4"><Value icon={<Sprout className="size-5" />} title="Field-tested expertise" text="Practical systems shaped by real apiary work and local conditions." /><Value icon={<UsersRound className="size-5" />} title="People-first training" text="Clear, hands-on learning that helps people build confidence." /><Value icon={<BadgeCheck className="size-5" />} title="Reliable guidance" text="Thoughtful support for each decision, from setup to harvest." /><Value icon={<Leaf className="size-5" />} title="Sustainable impact" text="Bee businesses that support livelihoods and healthier landscapes." /></div></section><div className="mt-8 rounded-2xl bg-amber-300 p-6 sm:flex sm:items-center sm:justify-between sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-800">Not sure where to begin?</p><h2 className="mt-2 font-serif text-2xl font-bold tracking-tight text-emerald-950">Let&apos;s find the right path together.</h2></div><Link href="/contact#booking-form" className="mt-5 inline-flex items-center gap-2 rounded-full bg-emerald-950 px-5 py-3 text-sm font-bold text-white transition hover:gap-3 hover:bg-emerald-800 sm:mt-0">Book a consultation <ArrowRight className="size-4" /></Link></div></section></main>;
}

function Value({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) {
  return <div className="flex gap-3"><span className="mt-0.5 text-amber-300">{icon}</span><div><h3 className="text-sm font-bold text-white">{title}</h3><p className="mt-1 text-sm leading-5 text-emerald-100/80">{text}</p></div></div>;
}
