import type { Metadata } from 'next';
import { ArrowRight } from 'lucide-react';
import Link from 'next/link';
import ServicesGrid from '@/components/services/ServicesGrid';
import { SERVICES } from '@/lib/services';

export const metadata: Metadata = { title: 'Services | Macaney Sustainable Solutions', description: 'Explore Macaney’s commercial apiary, agtech, training, and apiculture consultation services.' };

export default function ServicesPage() {
  return <main className="bg-stone-50 pt-16 text-stone-900 sm:pt-20"><section className="relative isolate overflow-hidden bg-emerald-950 px-4 pb-28 pt-16 text-white sm:px-6 sm:pb-36 sm:pt-20 lg:px-8"><div className="absolute -right-24 -top-16 size-96 rounded-full border border-emerald-700/50" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_0%,rgba(251,191,36,0.16),transparent_28%)]" /><div className="relative mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Our services</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-bold leading-[1.02] tracking-tight sm:text-6xl sm:leading-[0.98] lg:text-7xl">Practical expertise for every stage of the journey.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-emerald-100 sm:text-lg">Whether you are planning your first colonies or scaling a bee business, Macaney brings field-tested support built for Africa.</p></div><div aria-hidden="true" className="absolute -bottom-px left-1/2 h-16 w-[130%] -translate-x-1/2 rounded-t-[50%] bg-stone-50 sm:h-24" /></section><section className="mx-auto max-w-7xl px-4 pb-20 pt-8 sm:px-6 sm:pb-28 sm:pt-12 lg:px-8"><div className="mb-10 border-b border-emerald-900/15 pb-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Designed around your goals</p><h2 className="mt-2 font-serif text-3xl font-bold tracking-tight text-emerald-950 sm:text-4xl">Choose your next step.</h2></div><ServicesGrid services={SERVICES} /><div className="mt-12 rounded-[1.75rem] bg-amber-300 p-7 sm:flex sm:items-center sm:justify-between sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-800">Not sure where to begin?</p><h2 className="mt-3 font-serif text-3xl font-bold tracking-tight text-emerald-950">Let&apos;s find the right path together.</h2></div><Link href="/contact#booking-form" className="mt-6 inline-flex items-center gap-2 rounded-full bg-emerald-950 px-5 py-3 text-sm font-bold text-white transition hover:gap-3 hover:bg-emerald-800 sm:mt-0">Book a consultation <ArrowRight className="size-4" /></Link></div></section></main>;
}
